# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{post_policy}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micha\305\202 \305\201omnicki"]
  s.date = %q{2009-10-12}
  s.default_executable = %q{postpolicy.rb}
  s.description = %q{PostPolicy uses ACL system, which allow administrators to create rules based on mail source.}
  s.email = %q{michal@lomnicki.com.pl}
  s.executables = ["postpolicy.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/postpolicy.rb",
     "dbconfig.yml",
     "lib/postpolicy.rb",
     "lib/postpolicy/access_manager.rb",
     "lib/postpolicy/config.rb",
     "lib/postpolicy/extensions.rb",
     "lib/postpolicy/extensions/hash.rb",
     "lib/postpolicy/extensions/string.rb",
     "lib/postpolicy/logger.rb",
     "lib/postpolicy/plugins/acl/recipient.rb",
     "lib/postpolicy/plugins/acl/sender.rb",
     "lib/postpolicy/plugins/base/access.rb",
     "lib/postpolicy/plugins/base/acl.rb",
     "lib/postpolicy/plugins/base/datasource.rb",
     "lib/postpolicy/plugins/datasource/file.rb",
     "lib/postpolicy/plugins/datasource/regex.rb",
     "lib/postpolicy/plugins/datasource/sql.rb",
     "lib/postpolicy/plugins/datasource/value.rb",
     "lib/postpolicy/protocol.rb",
     "lib/postpolicy/rule.rb",
     "lib/postpolicy/server.rb",
     "lib/postpolicy/version.rb",
     "post_policy.gemspec",
     "postpolicy.yml",
     "spec/access_manager_spec.rb",
     "spec/acl_spec.rb",
     "spec/config_spec.rb",
     "spec/datasource_spec.rb",
     "spec/format_spec.rb",
     "spec/protocol_spec.rb",
     "spec/rule_spec.rb",
     "spec/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mlomnicki/post_policy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Postfix Policy Server in Ruby}
  s.test_files = [
    "spec/acl_spec.rb",
     "spec/access_manager_spec.rb",
     "spec/format_spec.rb",
     "spec/datasource_spec.rb",
     "spec/protocol_spec.rb",
     "spec/test_helper.rb",
     "spec/rule_spec.rb",
     "spec/config_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
